image: node:latest

before_script:
  - source ./.env  
  - apt-get -qq update
  - apt-get -qq install --yes python-dev 
  - apt-get -qq install --yes python-pip
  - pip install -U pip
  - pip install awscli --upgrade
  - echo $SITE_DOMAIN
  - aws --version
  - node -v
  - npm -v

stages:
  - master
  - staging
  - test

test-project:
  stage: test
  except:
    - master
    - staging
  script:
    - npm install
    - npm run test
    - npm run build

deploy-staging:
  stage: staging
  only:
    - staging
  script:
    - npm install
    - npm run test
    - npm run build
    - aws s3 cp --recursive ./public s3://$STAGING_ENV

deploy-master:
  stage: master
  only:
    - master
  script: 
    - npm install
    - npm run test
    - npm run build
    - aws s3 cp --recursive ./public s3://$SITE_DOMAIN
